export interface ProjectProps {
    id: number,
    title: string,
    category: string,
    status: string,
    descriptionPT: string,
    descriptionEN: string,
    details: string[],
    tecnologies: string[],
    finish: boolean,
    link: string,
    icon?: string,
    repoAvailability?: string,
    appLink?: string,
    imgPrincipal: string,
    imageContain?: boolean,
    imgMobile: string[],
    imgDesktop: string[],
    videos: string[],
    another: string [],
    anotherDescription: string []
}
